#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x41BC28FE99089D72 (simons@cryp.to)
#
Name     : autoconf-archive
Version  : 2019.01.06
Release  : 9
URL      : https://mirrors.kernel.org/gnu/autoconf-archive/autoconf-archive-2019.01.06.tar.xz
Source0  : https://mirrors.kernel.org/gnu/autoconf-archive/autoconf-archive-2019.01.06.tar.xz
Source1  : https://mirrors.kernel.org/gnu/autoconf-archive/autoconf-archive-2019.01.06.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: autoconf-archive-info = %{version}-%{release}
Requires: autoconf-archive-license = %{version}-%{release}
BuildRequires : sed

%description
Autoconf Archive
================
The GNU Autoconf Archive is a collection of more than 500 macros for [GNU
Autoconf](https://www.gnu.org/software/autoconf) that have been contributed
as free software by friendly supporters of the cause from all over the
Internet. Every single one of those macros can be re-used without imposing
any restrictions whatsoever on the licensing of the generated configure
script. In particular, it is possible to use all those macros in configure
scripts that are meant for non-free software. This policy is unusual for a
Free Software Foundation project. The FSF firmly believes that software
ought to be free, and software licenses like the GPL are specifically
designed to ensure that derivative work based on free software must be
free as well. In case of Autoconf, however, an exception has been made,
because Autoconf is at such a pivotal position in the software development
tool chain that the benefits from having this tool available as widely as
possible outweigh the disadvantage that some authors may choose to use it,
too, for proprietary software.

%package dev
Summary: dev components for the autoconf-archive package.
Group: Development
Provides: autoconf-archive-devel = %{version}-%{release}
Requires: autoconf-archive = %{version}-%{release}

%description dev
dev components for the autoconf-archive package.


%package doc
Summary: doc components for the autoconf-archive package.
Group: Documentation
Requires: autoconf-archive-info = %{version}-%{release}

%description doc
doc components for the autoconf-archive package.


%package info
Summary: info components for the autoconf-archive package.
Group: Default

%description info
info components for the autoconf-archive package.


%package license
Summary: license components for the autoconf-archive package.
Group: Default

%description license
license components for the autoconf-archive package.


%prep
%setup -q -n autoconf-archive-2019.01.06
cd %{_builddir}/autoconf-archive-2019.01.06

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605119927
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1605119927
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/autoconf-archive
cp %{_builddir}/autoconf-archive-2019.01.06/COPYING %{buildroot}/usr/share/package-licenses/autoconf-archive/e88f6aea9379eb98a7bbea965fc7127a64b41ad9
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/autoconf\-archive/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/autoconf-archive.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/autoconf-archive/e88f6aea9379eb98a7bbea965fc7127a64b41ad9
