#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x41BC28FE99089D72 (simons@cryp.to)
#
Name     : autoconf-archive
Version  : 2017.09.28
Release  : 3
URL      : https://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
Source0  : https://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
Source99 : https://ftp.gnu.org/gnu/autoconf-archive/autoconf-archive-2017.09.28.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: autoconf-archive-data
Requires: autoconf-archive-doc
BuildRequires : sed

%description
Autoconf Archive
================
The GNU Autoconf Archive is a collection of more than 500 macros for [GNU
Autoconf](https://www.gnu.org/software/autoconf) that have been contributed
as free software by friendly supporters of the cause from all over the
Internet. Every single one of those macros can be re-used without imposing
any restrictions whatsoever on the licensing of the generated configure
script. In particular, it is possible to use all those macros in configure
scripts that are meant for non-free software. This policy is unusual for a
Free Software Foundation project. The FSF firmly believes that software
ought to be free, and software licenses like the GPL are specifically
designed to ensure that derivative work based on free software must be
free as well. In case of Autoconf, however, an exception has been made,
because Autoconf is at such a pivotal position in the software development
tool chain that the benefits from having this tool available as widely as
possible outweigh the disadvantage that some authors may choose to use it,
too, for proprietary software.

%package data
Summary: data components for the autoconf-archive package.
Group: Data

%description data
data components for the autoconf-archive package.


%package dev
Summary: dev components for the autoconf-archive package.
Group: Development
Requires: autoconf-archive-data
Provides: autoconf-archive-devel

%description dev
dev components for the autoconf-archive package.


%package doc
Summary: doc components for the autoconf-archive package.
Group: Documentation

%description doc
doc components for the autoconf-archive package.


%prep
%setup -q -n autoconf-archive-2017.09.28

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506615055
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506615055
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/autoconf-archive/AUTHORS
/usr/share/autoconf-archive/COPYING
/usr/share/autoconf-archive/COPYING.EXCEPTION
/usr/share/autoconf-archive/README

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
